# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroCliente.ui'
#
# Created: Sun Oct 19 18:35:39 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(765, 558)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 510, 661, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.novocliente = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.novocliente.setFont(font)
        self.novocliente.setObjectName(_fromUtf8("novocliente"))
        self.horizontalLayout.addWidget(self.novocliente)
        self.editarcliente = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.editarcliente.setFont(font)
        self.editarcliente.setObjectName(_fromUtf8("editarcliente"))
        self.horizontalLayout.addWidget(self.editarcliente)
        self.removercliente = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.removercliente.setFont(font)
        self.removercliente.setObjectName(_fromUtf8("removercliente"))
        self.horizontalLayout.addWidget(self.removercliente)
        self.salvarcliente = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.salvarcliente.setFont(font)
        self.salvarcliente.setObjectName(_fromUtf8("salvarcliente"))
        self.horizontalLayout.addWidget(self.salvarcliente)
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 300, 258, 201))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.nota = QtGui.QTextEdit(self.layoutWidget1)
        self.nota.setObjectName(_fromUtf8("nota"))
        self.verticalLayout.addWidget(self.nota)
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 230, 651, 54))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.telefonecliente = QtGui.QLineEdit(self.layoutWidget2)
        self.telefonecliente.setObjectName(_fromUtf8("telefonecliente"))
        self.verticalLayout_2.addWidget(self.telefonecliente)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.emailcliente = QtGui.QLineEdit(self.layoutWidget2)
        self.emailcliente.setObjectName(_fromUtf8("emailcliente"))
        self.verticalLayout_3.addWidget(self.emailcliente)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_12 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.datenascimento = QtGui.QDateEdit(self.layoutWidget2)
        self.datenascimento.setObjectName(_fromUtf8("datenascimento"))
        self.verticalLayout_4.addWidget(self.datenascimento)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.layoutWidget3 = QtGui.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 170, 651, 54))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.spinBoxEstado = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBoxEstado.setObjectName(_fromUtf8("spinBoxEstado"))
        self.verticalLayout_5.addWidget(self.spinBoxEstado)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.cepcliente = QtGui.QLineEdit(self.layoutWidget3)
        self.cepcliente.setObjectName(_fromUtf8("cepcliente"))
        self.verticalLayout_6.addWidget(self.cepcliente)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_7.addWidget(self.label_8)
        self.paiscliente = QtGui.QLineEdit(self.layoutWidget3)
        self.paiscliente.setObjectName(_fromUtf8("paiscliente"))
        self.verticalLayout_7.addWidget(self.paiscliente)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.cpfcliente = QtGui.QLineEdit(self.layoutWidget3)
        self.cpfcliente.setObjectName(_fromUtf8("cpfcliente"))
        self.verticalLayout_8.addWidget(self.cpfcliente)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_9 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_9.addWidget(self.label_9)
        self.rgcliente = QtGui.QLineEdit(self.layoutWidget3)
        self.rgcliente.setObjectName(_fromUtf8("rgcliente"))
        self.verticalLayout_9.addWidget(self.rgcliente)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.layoutWidget4 = QtGui.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 30, 131, 52))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_12.addWidget(self.label)
        self.codigocliente = QtGui.QLineEdit(self.layoutWidget4)
        self.codigocliente.setObjectName(_fromUtf8("codigocliente"))
        self.verticalLayout_12.addWidget(self.codigocliente)
        self.layoutWidget5 = QtGui.QWidget(Form)
        self.layoutWidget5.setGeometry(QtCore.QRect(170, 30, 511, 52))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_2 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_13.addWidget(self.label_2)
        self.nomecliente = QtGui.QLineEdit(self.layoutWidget5)
        self.nomecliente.setObjectName(_fromUtf8("nomecliente"))
        self.verticalLayout_13.addWidget(self.nomecliente)
        self.layoutWidget6 = QtGui.QWidget(Form)
        self.layoutWidget6.setGeometry(QtCore.QRect(30, 100, 651, 54))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_3 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_11.addWidget(self.label_3)
        self.enderecocliente = QtGui.QLineEdit(self.layoutWidget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enderecocliente.sizePolicy().hasHeightForWidth())
        self.enderecocliente.setSizePolicy(sizePolicy)
        self.enderecocliente.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.enderecocliente.setObjectName(_fromUtf8("enderecocliente"))
        self.verticalLayout_11.addWidget(self.enderecocliente)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_4 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_10.addWidget(self.label_4)
        self.cidadecliente = QtGui.QLineEdit(self.layoutWidget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cidadecliente.sizePolicy().hasHeightForWidth())
        self.cidadecliente.setSizePolicy(sizePolicy)
        self.cidadecliente.setObjectName(_fromUtf8("cidadecliente"))
        self.verticalLayout_10.addWidget(self.cidadecliente)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.novocliente.setText(_translate("Form", "Novo Cliente", None))
        self.editarcliente.setText(_translate("Form", "Editar Cadastro", None))
        self.removercliente.setText(_translate("Form", "Remover Cliente", None))
        self.salvarcliente.setText(_translate("Form", "Confirmar/Salvar", None))
        self.label_13.setText(_translate("Form", "Notas.", None))
        self.label_10.setText(_translate("Form", "Telefone", None))
        self.label_11.setText(_translate("Form", "E-mail", None))
        self.label_12.setText(_translate("Form", "Data de Nascimento", None))
        self.label_5.setText(_translate("Form", "Estado", None))
        self.label_6.setText(_translate("Form", "CEP", None))
        self.label_8.setText(_translate("Form", "País/Região", None))
        self.label_7.setText(_translate("Form", "CPF", None))
        self.label_9.setText(_translate("Form", "RG", None))
        self.label.setText(_translate("Form", "Código(auto)", None))
        self.label_2.setText(_translate("Form", "Nome do Cliente", None))
        self.label_3.setText(_translate("Form", "Endereço", None))
        self.label_4.setText(_translate("Form", "Cidade", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

